---
title: "Analises_"
date: "2024-01-22"
output:
  word_document: default
  html_document: default
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, 
  message = FALSE, 
  error = FALSE, 
  warning = FALSE,
  comment = "#>"
)
```

### Carregando bibliotecas
```{r}
library(tidyverse)
library(geobr)
source("R/gafico.R")
source("R/my-function.R")
```

### Carregando as bases de dados

```{r}
emissions_sources <- read_rds("data/emissions_sources.rds") %>% 
  mutate(source_name_1 = str_to_title(source_name))
states <- read_rds("data/states.rds") %>% 
  mutate(name_region = ifelse(name_region == "Centro Oeste","Centro-Oeste",name_region))

brazil_ids <- read_rds("data/df_nome.rds")
glimpse(emissions_sources)
nomes_uf <- c(brazil_ids$nome_uf %>% unique(),"Brazil")
abbrev_states <- brazil_ids$sigla_uf %>% unique()
region_names <- brazil_ids$nome_regiao %>% unique()
```


### Mapeando  Fontes e Sumidouros

```{r}

anos <- 2015:2022

for(i in seq_along(anos)){
  plot_source_sink <- biomes |>
    filter(name_biome!='Sistema Costeiro') |> 
  ggplot() +
  geom_sf(fill="white", color="black",
          size=.15, show.legend = FALSE) +
  geom_point(
    data = emissions_sources |> 
    filter(year == anos[i],
           gas == "co2e_100yr",
           !source_name %in% nomes_uf,
           !sub_sector %in% c("forest-land-clearing",
                              "forest-land-degradation",
                              "shrubgrass-fires",
                              "forest-land-fires",
                              "wetland-fires",
                              "removals")
    ) %>% 
    group_by(lon,lat,city_ref) %>% 
    summarise(
      emission = sum(emissions_quantity, na.rm=TRUE)
    ) %>% 
    mutate(
      fonte_sumidouro = ifelse(emission <=0, "Sink","Source")
      ),
    aes(lon,lat,color=fonte_sumidouro),
    alpha=.25) +
    scale_color_manual(values = c("green","darkred"))+
    tema_mapa()+
    labs(x='Longitude',y='Latitude',col=expression('CO'[2]~'eq'))
    
  
  ggplot2::ggsave(paste0('img/source_sink_',anos[i],'.png'),
                  units="in", width=8, height=6,
                  dpi=1000)
  print(plot_source_sink)
}
 

```


```{r}
emissions_sources |>
  filter(year > 2018 & year < 2023,
           gas == "co2e_100yr",
           !source_name %in% nomes_uf,
           !sub_sector %in% c("forest-land-clearing",
                              "forest-land-degradation",
                              "shrubgrass-fires",
                              "forest-land-fires",
                              "wetland-fires",
                              "removals")
    ) |> 
  mutate(
    region = case_when(
      nome_regiao=='Norte'~'North',
      nome_regiao=='Nordeste'~'Northeast',
      nome_regiao=='Sul'~'South',
      nome_regiao=='Sudeste'~'Southeast',
      nome_regiao=='Centro-Oeste'~'Midweast',
      .default = 'Other'
      )
    ) |> 
    group_by(region,year) |>
  filter(year!=2019) |> 
    summarise(
      ghg_balance = sum(emissions_quantity, na.rm=TRUE)
    ) |> 
  ggplot(aes(x=year,y=ghg_balance/1e6,fill=region))+
  geom_col(position = 'dodge')+
  scale_fill_viridis_d()+
  labs(x='Year',y=expression('CO'[2]~'eq Balance (M ton  CO'[2]~'eq '~year^-1~')'),fill='Region')

```


```{r}
emissions_sources |>
  filter(year > 2018 & year < 2023,
           gas == "co2e_100yr",
           !source_name %in% nomes_uf,
           !sub_sector %in% c("forest-land-clearing",
                              "forest-land-degradation",
                              "shrubgrass-fires",
                              "forest-land-fires",
                              "wetland-fires",
                              "removals")
    ) |> 
  mutate(
    region = case_when(
      nome_regiao=='Norte'~'North',
      nome_regiao=='Nordeste'~'Northeast',
      nome_regiao=='Sul'~'South',
      nome_regiao=='Sudeste'~'Southeast',
      nome_regiao=='Centro-Oeste'~'Midweast',
      .default = 'Other'
      )
    ) |> 
    group_by(region,sub_sector,year) |> 
  filter(year!=2019) |> 
    summarise(
      ghg_balance = sum(emissions_quantity, na.rm=TRUE)
    ) |> 
  ggplot(aes(x=year,y=ghg_balance/1e6,fill=sub_sector))+
  geom_col(position = 'dodge')+
  scale_fill_viridis_d()+
  facet_wrap(~region,scales='free')+
  labs(x='Year',y=expression('CO'[2]~'eq Balance (M ton  CO'[2]~'eq '~ year^-1~')'),fill='Sector')

ggplot2::ggsave('img/co2_balance_sector.png',
                units="in",width=10,heigh=6,dpi=1000)

```


```{r}
emissions_sources |>
  filter(year > 2018 & year < 2023,
           gas == "co2e_100yr",
           !source_name %in% nomes_uf,
           !sub_sector %in% c("forest-land-clearing",
                              "forest-land-degradation",
                              "shrubgrass-fires",
                              "forest-land-fires",
                              "wetland-fires",
                              "removals")
    ) |> 
  mutate(
    region = case_when(
      nome_regiao=='Norte'~'North',
      nome_regiao=='Nordeste'~'Northeast',
      nome_regiao=='Sul'~'South',
      nome_regiao=='Sudeste'~'Southeast',
      nome_regiao=='Centro-Oeste'~'Midweast',
      .default = 'Other'
      )
    ) |> 
    group_by(year) |> 
  filter(year!=2019) |> 
    summarise(
      ghg_balance = sum(emissions_quantity, na.rm=TRUE)
    ) |> 
  ggplot(aes(x=year,y=ghg_balance/1e6))+
  geom_col(position = 'dodge')+
  scale_fill_viridis_d()+
  labs(x='Year',y=expression('CO'[2]~'eq Balance (M ton  CO'[2]~'eq '~ year^-1~')'),fill='Sector')
```


```{r}
emissions_sources |>
  filter(year > 2018 & year < 2023,
           gas == "co2e_100yr",
           !source_name %in% nomes_uf,
           !sub_sector %in% c("forest-land-clearing",
                              "forest-land-degradation",
                              "shrubgrass-fires",
                              "forest-land-fires",
                              "wetland-fires",
                              "removals")
    ) |> 
  mutate(
    region = case_when(
      nome_regiao=='Norte'~'North',
      nome_regiao=='Nordeste'~'Northeast',
      nome_regiao=='Sul'~'South',
      nome_regiao=='Sudeste'~'Southeast',
      nome_regiao=='Centro-Oeste'~'Midweast',
      .default = 'Other'
      )
    ) |> 
    group_by(year,sub_sector) |> 
  filter(year!=2019) |> 
    summarise(
      ghg_balance = sum(emissions_quantity, na.rm=TRUE)
    ) |> 
  #filter(sub_sector=='agriculture') |> 
  mutate(ghg_balance=ghg_balance/1e6) |> 
  ggplot(aes(x=year,y=ghg_balance,fill=sub_sector))+
  geom_col(position = 'dodge')+
  scale_fill_viridis_d()+
  labs(x='Year',
       y=expression('CO'[2]~'eq Balance (M ton  CO'[2]~'eq '~year^-1~')'),
       fill='Sector')

ggplot2::ggsave('img/co2_brazil_balance_sector.png',
                units="in",width=8,heigh=6,dpi=1000)
```
## Análise por bioma

```{r}
biomes <- geobr::read_biomes()
biomes |> 
  filter(name_biome!='Sistema Costeiro') |> 
  ggplot(aes(fill=name_biome))+
  geom_sf()+
  tema_mapa()


emissions_sources |> 
  ggplot(aes(x=lon,y=lat,color=biome))+
  geom_point()
```

```{r}

emissions_sources |> 
  filter(year > 2018 & year < 2023,
           gas == "co2e_100yr",
           !source_name %in% nomes_uf,
           !sub_sector %in% c("forest-land-clearing",
                              "forest-land-degradation",
                              "shrubgrass-fires",
                              "forest-land-fires",
                              "wetland-fires",
                              "removals")
    ) |> 
  ggplot(aes(x=lon,y=lat,col=biome))+
  geom_point()
  
```




```{r}
emissions_sources |>
  filter(year > 2018 & year < 2023,
           gas == "co2e_100yr",
           !source_name %in% nomes_uf,
           !sub_sector %in% c("forest-land-clearing",
                              "forest-land-degradation",
                              "shrubgrass-fires",
                              "forest-land-fires",
                              "wetland-fires",
                              "removals")
    ) |>  
    group_by(biome,year) |> 
  filter(year!=2019) |> 
    summarise(
      ghg_balance = sum(emissions_quantity, na.rm=TRUE)
    ) |> 
  ggplot(aes(x=year,y=ghg_balance/1e6,fill=biome))+
  geom_col(position = 'dodge')+
  scale_fill_viridis_d()+
  labs(x='Year',y=expression('CO'[2]~'eq Balance (M ton  CO'[2]~'eq '~year^-1~')'),fill='Biome')

```

```{r}
emissions_sources |>
  filter(year > 2018 & year < 2023,
           gas == "co2e_100yr",
           !source_name %in% nomes_uf,
           !sub_sector %in% c("forest-land-clearing",
                              "forest-land-degradation",
                              "shrubgrass-fires",
                              "forest-land-fires",
                              "wetland-fires",
                              "removals")
    ) |> 
    group_by(biome,sub_sector,year) |> 
  filter(year!=2019) |> 
    summarise(
      ghg_balance = sum(emissions_quantity, na.rm=TRUE)
    ) |> 
  ggplot(aes(x=year,y=ghg_balance/1e6,fill=sub_sector))+
  geom_col(position = 'dodge')+
  scale_fill_viridis_d()+
  facet_wrap(~biome,scales='free')+
  labs(x='Year',
       y=expression('CO'[2]~'eq Balance (M ton '[2]~'eq'~year^-1~')'),
       fill='Biome')
ggplot2::ggsave('img/co2_balance_sector_biomes.png',
                units="in",width=10,heigh=6,dpi=1000)

```


```{r}
emissions_sources |>
  filter(year > 2018 & year < 2023,
           gas == "co2e_100yr",
           !source_name %in% nomes_uf,
           !sub_sector %in% c("forest-land-clearing",
                              "forest-land-degradation",
                              "shrubgrass-fires",
                              "forest-land-fires",
                              "wetland-fires",
                              "removals")
    ) |> 
  #group_by(biomes,year) |>
  filter(year!=2019) |> 
  ggplot(aes(x=emissions_quantity/1e6,
             y=as.factor(year),
             fill=as.factor(year)
             ))+
  ggridges::geom_density_ridges(alpha=.4)+
  facet_wrap(~biome,scales = 'free_x')
  #xlim(-2.5,2.5)

```


```{r}
emissions_sources |>
  filter(year > 2014 & year < 2023,
           gas == "co2e_100yr",
           !source_name %in% nomes_uf,
           !sub_sector %in% c("forest-land-clearing",
                              "forest-land-degradation",
                              "shrubgrass-fires",
                              "forest-land-fires",
                              "wetland-fires",
                              "removals")
    ) |> 
    group_by(biome,sub_sector,year) |> 
    summarise(
      ghg_balance = round(sum(emissions_quantity, na.rm=TRUE)/1e9,4)
    )
```


```{r}

biomes |>
  filter(name_biome!='Sistema Costeiro') |> 
  ggplot() +
  geom_sf(fill="white", color="black",
          size=.15, show.legend = FALSE) +
  geom_point(
    data = emissions_sources |> 
    filter(year == 2022,
           gas == "co2e_100yr",
           !source_name %in% nomes_uf,
           sub_sector %in% c("forest-land-clearing",
                              "forest-land-degradation",
                              "shrubgrass-fires",
                              "forest-land-fires",
                              "wetland-fires",
                              "removals")
    ) |>
    group_by(lon,lat,sub_sector) %>% 
    summarise(
      emission = sum(emissions_quantity, na.rm=TRUE)
    ) %>% 
    mutate(
      fonte_sumidouro = ifelse(emission <=0, "Sink","Source")
      ),
    aes(lon,lat,col=fonte_sumidouro),
    alpha=.25
    ) +
    scale_color_manual(values = c("green","darkred"))+
    tema_mapa()+
    labs(x='Longitude',y='Latitude',col=expression('CO'[2]~'eq'))

```
```{r}
emissions_sources |> 
  filter(year>2014 & year < 2023) |> 
    filter(gas == "co2e_100yr",
           !source_name %in% nomes_uf,
           sub_sector %in% c("forest-land-clearing",
                              "forest-land-degradation",
                              "shrubgrass-fires",
                              "forest-land-fires",
                              "wetland-fires",
                              "removals")|
             sector_name=='forestry'
    ) |> 
    group_by(sub_sector,year) %>%
    summarise(
      emission = sum(emissions_quantity, na.rm=TRUE)
    ) %>%
  ggplot(aes(x=sub_sector,y=emission/1e9,group=year,
             fill=forcats::as_factor(year)))+
  geom_col(position = 'dodge')+
  scale_fill_viridis_d()+
  labs(x='',
       y=expression('Emission (G ton )'),
       fill='Year')+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 35, vjust = 1, hjust=1))
  
  
```

