---
title: "Cidades-Unesp"
author: "Panosso AR"
date: "2024-01-22"
output:
  word_document: default
  html_document: default
---
### Carregando bibliotecas
```{r}
library(tidyverse)
library(geobr)
source("R/gafico.R")
```

### Carregando as bases de dados

```{r}
emissions_sources <- read_rds("data/emissions_sources.rds") %>% 
  mutate(source_name_1 = str_to_title(source_name))
states <- read_rds("data/states.rds") %>% 
  mutate(name_region = ifelse(name_region == "Centro Oeste","Centro-Oeste",name_region))

brazil_ids <- read_rds("data/df_nome.rds")
glimpse(emissions_sources)
nomes_uf <- c(brazil_ids$nome_uf %>% unique(),"Brazil")
abbrev_states <- brazil_ids$sigla_uf %>% unique()
region_names <- brazil_ids$nome_regiao %>% unique()
```

### tabela resumo

```{r}
emissions_sources %>% 
  filter(
    year == 2022,
    gas == "co2e_100yr",
    !source_name %in% nomes_uf,
    !sub_sector %in% c("forest-land-clearing",
                            "forest-land-degradation",
                            "shrubgrass-fires",
                            "forest-land-fires",
                            "wetland-fires",
                            "removals")
    ) %>% 
  group_by(source_name) %>% 
  summarise(
    emission = mean(emissions_quantity, na.rm=TRUE)
  ) %>% 
  arrange(emission %>% desc()) %>% 
  mutate(
    acumulada = cumsum(emission)
    ) 
```

```{r}
emissions_sources %>% 
  filter(str_detect(city_ref,"Botucatu"),
         # city_ref == "Santos",
         sigla_uf == "SP",
         year == 2022,
         gas == "co2e_100yr",
         !source_name %in% nomes_uf,
         !sub_sector %in% c("forest-land-clearing",
                            "forest-land-degradation",
                            "shrubgrass-fires",
                            "forest-land-fires",
                            "wetland-fires",
                            "removals")
         ) %>% 
  group_by(sector_name,source_name,sub_sector) %>% 
  summarise(
    emission = mean(emissions_quantity, na.rm=TRUE)
  ) %>% 
  arrange(emission )  %>% 
  ungroup() %>% 
  mutate(Cumsum = cumsum(emission)) 
  
# nomenclatura no site
# net-forest-land => Forest land
# net-wetland => Wetland
# net-shrubgrass => Net shrubgrass
# cropland-fires => Crop fire
# synthetic-fertilizer-application => Crop field
# enteric-fermentation-cattle-pasture => Cattle pasture
# manure-left-on-pasture-cattle => Pasture cattle
```
###


```{r}
# unidades unesp
cidades_unesp <- read.table("data-raw/unidades-unesp.txt", h=TRUE) %>% 
  pull(V1)

for(i in seq_along(cidades_unesp)){
  resumo_unesp<-emissions_sources %>% 
    filter(str_detect(city_ref,cidades_unesp[i]),
           sigla_uf == "SP",
           year == 2022,
           gas == "co2e_100yr",
           !source_name %in% nomes_uf,
           !sub_sector %in% c("forest-land-clearing",
                              "forest-land-degradation",
                              "shrubgrass-fires",
                              "forest-land-fires",
                              "wetland-fires",
                              "removals")
    ) %>% 
    group_by(sector_name,source_name,sub_sector) %>% 
    summarise(
      emission = mean(emissions_quantity, na.rm=TRUE)
    ) %>% 
    arrange(emission )  %>% 
    ungroup() %>% 
    mutate(Cumsum = cumsum(emission))
  print(resumo_unesp)
  } 

```

```{r}
states  %>%
  #filter(name_state == "São Paulo") |> 
  ggplot() +
  geom_sf(fill="white", color="black",
          size=.15, show.legend = FALSE) +
  geom_point(
    data = emissions_sources %>% 
    filter(#str_detect(city_ref,str_c(cidades_unesp,collapse = "|")),
           #sigla_uf == "SP",
           year == 2019,
           gas == "co2e_100yr",
           !source_name %in% nomes_uf,
           !sub_sector %in% c("forest-land-clearing",
                              "forest-land-degradation",
                              "shrubgrass-fires",
                              "forest-land-fires",
                              "wetland-fires",
                              "removals")
    ) %>% 
    group_by(lon,lat,city_ref) %>% 
    summarise(
      emission = sum(emissions_quantity, na.rm=TRUE)
    ) %>% 
    mutate(
      fonte_sumidouro = ifelse(emission <=0, "Sumidouro","Fonte")
      ),
    aes(lon,lat,color=fonte_sumidouro)) +
    scale_color_manual(values = c("red","green"))+
  tema_mapa()
```

```{r}
ano <- 2013:2022
for(i in seq_along(ano)){
  plot_unesp <- emissions_sources %>% 
    filter(str_detect(city_ref,str_c(cidades_unesp,collapse = "|")),
           sigla_uf == "SP",
           year == ano[i],
           gas == "co2e_100yr",
           !source_name %in% nomes_uf,
           !sub_sector %in% c("forest-land-clearing",
                              "forest-land-degradation",
                              "shrubgrass-fires",
                              "forest-land-fires",
                              "wetland-fires",
                              "removals")
    ) %>% 
    group_by(city_ref) %>% 
    summarise(
      emission = sum(emissions_quantity, na.rm=TRUE)
    ) %>% 
    mutate(
      city_ref = city_ref %>% fct_reorder(emission),
      fonte_sumidouro = ifelse(emission <=0, "Sumidouro","Fonte"),
    ) %>%
    ggplot(aes(x=city_ref, y= emission, fill=fonte_sumidouro))+
    geom_col(color="black") +
    coord_flip() +
    theme_bw() +
    labs(title = paste("UNESP-Cidades (",ano[i],")"),
         y="(emission)") +
    scale_fill_manual(values = c("red","green"))
  print(plot_unesp)
  }
```

