---
title: "Precipitação"
date: "2024-01-25"
output:
  word_document: default
  html_document: default
---
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, 
  message = FALSE, 
  error = FALSE, 
  warning = FALSE,
  comment = "#>"
)
```

### Carregando bibliotecas
```{r}
library(tidyverse)
library(geobr)
source("R/gafico.R")
source("R/my-function.R")
```

### Carregando dados
```{r}
file_name <- list.files('precipitation/data/',full.names = T)
df <- read_rds(file_name)
```


### Processando dados de precipitação 
```{r}
df_n <- df |>
  mutate(year= year(YYYYMMDD),
                month = month(YYYYMMDD),
                longitude=LON,
                latitude=LAT) |>
  group_by(longitude, latitude, year) |>
  summarise(
    prec = sum(PRECTOTCORR)
  ) 


```


## Plot Precipitação
```{r}
anos <-2015:2022
  

for(i in seq_along(anos)){
  plot_prec <- biomes |> 
    filter(name_biome!='Sistema Costeiro') |> 
    ggplot() +
    geom_sf(fill="white", color="black",
          size=.15, show.legend = FALSE)+
    geom_tile(data= df_n |> 
                filter(year==anos[i]) |> 
                mutate(
                  prec_n = case_when(
                    prec < 500 ~ '< 500',
                    prec <= 1000 ~ '<= 1000',
                    prec <= 1500 ~ '<= 1500',
                    prec <= 2000 ~ '<= 2000',
                    prec <= 2500 ~ '<= 2500',
                    prec <= 3000 ~ '<= 3000',
                    prec > 3000~ '> 3000'
                    )
                  ),
              aes(x=longitude,y=latitude,fill=prec_n),
              alpha=.6
              )+
    scale_fill_manual(values=c('darkred','tan1',
                                        'seagreen1','skyblue1',
                                        'dodgerblue1','mediumblue',
                                        'navy')
                                        )+
    tema_mapa()+
    theme_bw()+
    labs(x='Longitude',y='Latitude',
         fill=expression('Precipitation (mm year'^-1~')'))
  ggplot2::ggsave(paste0('img/precipitacao_media_',anos[i],'.png'),
                  units="in", width=8, height=6,
                  dpi=1000)
  print(plot_prec)
}
```
```{r}
df_n |>
  mutate(
    biomes = get_geobr_biomes(longitude,latitude)
  ) |>
  mutate(
    biomes_n =
      case_when(
        biomes=='Other'& longitude>=-45 & latitude <0~'AF',
        biomes=='Amazônia'~'AMZ',
        biomes=='Other'& longitude< -45 & latitude >=-10 ~'AMZ',
        biomes == 'Mata Atlântica' ~ 'AF',
        biomes=='Cerrado'~'CERR',
        biomes =='Pampa'~'PMP',
        biomes == 'Pantanal' ~ 'PNT',
        biomes=='Caatinga'~'CAAT',
        .default = 'Other'
      )
  ) |> 
  ggplot(aes(x=prec,y=as.factor(year)))+
  geom_boxplot()+
  facet_wrap(~biomes_n,scales='free_x')+
  labs(x='Precipitation (mm)',
       y='year',
       fill=''
  )+
  theme_bw()


ggplot2::ggsave('img/prec_box.png',
                  units="in", width=8, height=6,
                  dpi=1000)
```

```{r}
df_n |>
  filter(year!=2023) |> 
  mutate(
    biomes = get_geobr_biomes(longitude,latitude)
  ) |>
  mutate(
    biomes_n =
      case_when(
        biomes=='Other'& longitude>=-45 & latitude <0~'AF',
        biomes=='Amazônia'~'AMZ',
        biomes=='Other'& longitude< -45 & latitude >=-10 ~'AMZ',
        biomes == 'Mata Atlântica' ~ 'AF',
        biomes=='Cerrado'~'CERR',
        biomes =='Pampa'~'PMP',
        biomes == 'Pantanal' ~ 'PNT',
        biomes=='Caatinga'~'CAAT',
        .default = 'Other'
      )
  ) |>
  filter(biomes_n=='CAAT') |> 
  arrange(prec)
```
```{r}
df_n |>
  filter(year!=2023) |> 
  mutate(
    biomes = get_geobr_biomes(longitude,latitude)
  ) |>
  mutate(
    biomes_n =
      case_when(
        biomes=='Other'& longitude>=-45 & latitude <0~'AF',
        biomes=='Amazônia'~'AMZ',
        biomes=='Other'& longitude< -45 & latitude >=-10 ~'AMZ',
        biomes == 'Mata Atlântica' ~ 'AF',
        biomes=='Cerrado'~'CERR',
        biomes =='Pampa'~'PMP',
        biomes == 'Pantanal' ~ 'PNT',
        biomes=='Caatinga'~'CAAT',
        .default = 'Other'
      )
  ) |> 
  filter(biomes_n!='Other') |> 
  group_by(biomes_n,year) |> 
  summarise(prec=mean(prec)) |> 
  ggplot(aes(x=year,y=prec,col=biomes_n))+
  geom_point()+
  geom_smooth(method = 'lm',se=F)+
  ggpubr::stat_cor()+
  labs(x='',
       y='Precipitation',
       col='Biome')+
  ylim(0,3000)+
  theme_bw()
```

```{r}
df |>
  mutate(year= year(YYYYMMDD),
                month = month(YYYYMMDD),
                longitude=LON,
                latitude=LAT) |>
  group_by(longitude, latitude, year, month) |>
  summarise(
    prec = sum(PRECTOTCORR)
  ) |> 
  filter(year!=2023) |> 
  mutate(
    biomes = get_geobr_biomes(longitude,latitude)
  ) |>
  mutate(
    biomes_n =
      case_when(
        biomes=='Other'& longitude>=-45 & latitude <0~'AF',
        biomes=='Amazônia'~'AMZ',
        biomes=='Other'& longitude< -45 & latitude >=-10 ~'AMZ',
        biomes == 'Mata Atlântica' ~ 'AF',
        biomes=='Cerrado'~'CERR',
        biomes =='Pampa'~'PMP',
        biomes == 'Pantanal' ~ 'PNT',
        biomes=='Caatinga'~'CAAT',
        .default = 'Other'
      )
  ) |> 
  filter(biomes_n!='Other') |> 
  group_by(biomes_n,year,month) |> 
  summarise(prec=mean(prec)) |> 
  dplyr::mutate(date=make_date(year,month,'15')) |> 
  ggplot(aes(x=date,y=prec,col=biomes_n))+
  geom_point()+
  geom_smooth(method = 'lm',se=F)+
  ggpubr::stat_cor()
```

```{r}
df |>
  mutate(year= year(YYYYMMDD),
                month = month(YYYYMMDD),
                longitude=LON,
                latitude=LAT) |>
  group_by(longitude, latitude, year, month) |>
  summarise(
    prec = sum(PRECTOTCORR)
  ) |> 
  filter(year!=2023) |> 
  mutate(
    biomes = get_geobr_biomes(longitude,latitude)
  ) |>
  mutate(
    biomes_n =
      case_when(
        biomes=='Other'& longitude>=-45 & latitude <0~'AF',
        biomes=='Amazônia'~'AMZ',
        biomes=='Other'& longitude< -45 & latitude >=-10 ~'AMZ',
        biomes == 'Mata Atlântica' ~ 'AF',
        biomes=='Cerrado'~'CERR',
        biomes =='Pampa'~'PMP',
        biomes == 'Pantanal' ~ 'PNT',
        biomes=='Caatinga'~'CAAT',
        .default = 'Other'
      )
  ) |> 
  filter(biomes_n=='CAAT') |> 
  group_by(biomes_n,year,month) |> 
  summarise(prec=mean(prec)) |> 
  pull(prec) |> 
  trend::mk.test()
```

