---
title: "SIF analise"
date: "2024-01-24"
output:
  word_document: default
  html_document: default
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, 
  message = FALSE, 
  error = FALSE, 
  warning = FALSE,
  comment = "#>"
)
```

### Carregando bibliotecas
```{r}
library(tidyverse)
library(geobr)
source("R/gafico.R")
source("R/my-function.R")
source("SIF/r/function.R")
```



### Carregando dados

```{r}


sif_file <- list.files('SIF/data/',full.names = T)
sif_df <- read_rds(sif_file) |> filter(year>2014 & year <2023) 
  

states <- read_rds("data/states.rds") |> 
  mutate(name_region = ifelse(name_region == "Centro Oeste","Centro-Oeste",name_region))
```


####

```{r}
sifdf_filter <- sif_df |>
  #dplyr::filter(year == 2015) |>
  dplyr::filter(dist_sif<0.25) |>
  dplyr::mutate(
    lon = lon_grid,
    lat = lat_grid,
  ) |>
  dplyr::select(-c(lon_grid,lat_grid)) |>
  dplyr::group_by(lon,lat,year,month) |>
  dplyr::summarise(
    sif_mean= mean(sif_757,na.rm=TRUE),
    sif_sd = sd(sif_757,na.rm=TRUE),
    sza = mean(sza),
    nobs = dplyr::n(),
    sif_ep = sif_sd/sqrt(nobs),
    cv = 100*sif_sd/sif_mean
  ) |>
  dplyr::mutate(
    date = lubridate::make_date(year,month,'15')
  )

```


```{r}

sifdf_filter |>
  dplyr::group_by(date) |>
  dplyr::summarise(sif_mean=mean(sif_mean)) |>
  ggplot2::ggplot(ggplot2::aes(x=date,y=sif_mean )) +
  ggplot2::geom_point(shape=21,color="black",fill="gray") +
  ggplot2::geom_line(color="red") +
  ggplot2::geom_smooth(method = "lm") +
  ggpubr::stat_regline_equation(ggplot2::aes(
    label =  paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~~"))) +
  ggplot2::theme_bw()+
  ggplot2::xlab('Date')+
  ggplot2::ylab(expression(
    'SIF 757nm (Wm'^-2~'sr'^-1~mu~'m'^-1~')'
  ))
```

```{r}
sif_nest <- sifdf_filter |>
  tibble::as_tibble() |>
  dplyr::mutate(year =lubridate::year(date),
                quarter = lubridate::quarter(date),
                quarter_year = lubridate::make_date(year, quarter, 1)) |>
  dplyr::group_by(lon, lat,date) |>
  dplyr::summarise(sif = mean(sif_mean, na.rm=TRUE)) |>
  dplyr::mutate(
    id_time = date
  ) |>
  dplyr::group_by(lon,lat) |>
  tidyr::nest()

### calculating for each pixel
sif_nest_ <- sif_nest|>
  dplyr::mutate(
    beta_line = purrr::map(data,linear_reg, output="beta1"),
    p_value = purrr::map(data,linear_reg, output="p_value"),
    partial = purrr::map(data,linear_reg, output="partial"),
    n_obs = purrr::map(data,linear_reg, output="n"),
    beta_error=purrr::map(data,linear_reg,output='betaerror'),
    model_error=purrr::map(data,linear_reg,output='modelerror')
  )

```


```{r}
sif_nest_new <- sif_nest_ |>
  dplyr::filter(n_obs > 12) |>
  tidyr::unnest(cols = c(beta_line, partial,beta_error,model_error)) |>
  dplyr::ungroup() |>
  dplyr::select(lon, lat, beta_line, partial,beta_error,model_error)

q3_sif <- sif_nest_new |> dplyr::pull(beta_line) |> quantile(.75)
q1_sif <- sif_nest_new |> dplyr::pull(beta_line) |> quantile(.25)

```

```{r}
states |>
  ggplot2::ggplot()+
  ggplot2::geom_sf(fill="white", color="black",
                   size=.15, show.legend = FALSE)+
  ggplot2::geom_point(data=sif_nest_new |>
                        dplyr::mutate(
                          sif = dplyr::case_when(
                            beta_line > q3_sif ~ 'Enhancement',
                            beta_line < q1_sif ~'Decreasing',
                            .default = 'Non Significant'
                          )
                        ) |>
                        dplyr::filter(sif!='Non Significant'),
                      ggplot2::aes(x=lon,y=lat,col=sif),
  )+
  ggplot2::scale_color_viridis_d()+
  tema_mapa()+
  ggplot2::labs(x='Longitude',y='Latitude',col=expression('β (Wm'^-2~'sr'^-1~mu~'m'^-1~')'))
```
```{r}
write.csv(sif_nest_new |>
                        dplyr::mutate(
                          sif = dplyr::case_when(
                            beta_line > q3_sif ~ 'Enhancement',
                            beta_line < q1_sif ~'Decreasing',
                            .default = 'Non Significant'
                          )
                        ) |>
                        dplyr::filter(sif!='Non Significant'),
          "SIF/data/trend.csv")
```

